blank_issues_enabled: false
contact_links:
  - name: FiniteMachine Community Discussions
    url: https://github.com/piotrmurach/finite_machine/discussions
    about: Suggest ideas, ask and answer questions
